# Generated by Django 5.1.2 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='username',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
