version: '3'

services:
  usuariosapi:
    build:
      context: ./UsuariosAPI
    container_name: usuariosapi
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=finanzauto
      - DB_USER=ser0710
      - DB_PASSWORD=Prueba_fin
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  publicacionesapi:
    build:
      context: ./PublicacionesAPI
    container_name: publicacionesapi
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=finanzauto
      - DB_USER=ser0710
      - DB_PASSWORD=Prueba_fin
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: finanzauto
      POSTGRES_USER: ser0710
      POSTGRES_PASSWORD: Prueba_fin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  frontend:
    build:
      context: ./front
    container_name: front
    ports:
      - "3000:3000"
      
volumes:
  postgres_data: